<a href="https://colab.research.google.com/github/kiran-12371/Pandas-task/blob/main/PandasTask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Kiran iqbal**

**Roll No:874229**

In [ ]:
import pandas as pd

In [ ]:
#Reading a data set
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Social_media_impact_on_life.csv")
print(df)

       Student_ID  Age  Gender Academic_Level Primary_Platform  \
0     STU_2024000   19  Female  Undergraduate         Snapchat
1     STU_2024001   19  Female  Undergraduate        Instagram
2     STU_2024002   17  Female    High School           TikTok
3     STU_2024003   16  Female    High School          YouTube
4     STU_2024004   17    Male    High School         LinkedIn
...           ...  ...     ...            ...              ...
4495  STU_2028495   16    Male    High School          YouTube
4496  STU_2028496   19  Female  Undergraduate         LinkedIn
4497  STU_2028497   19    Male  Undergraduate        Instagram
4498  STU_2028498   16    Male    High School         LinkedIn
4499  STU_2028499   24    Male  Undergraduate        Instagram

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
0                   7.5                  1.5  Smartphone
1                   4.6                  1.3  Smartphone
2                  10.9                  1.7  Smartphone
3                   6.0                  2.3      Tablet
4                   3.3                  2.6  Smartphone
...                 ...                  ...         ...
4495                5.8                  1.2  Smartphone
4496                3.8                  3.0  Smartphone
4497                7.7                  1.1  Smartphone
4498                4.6                  3.3   Laptop/PC
4499                1.8                  2.1  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
0                      5.9                    2              True
1                      7.9                    3              True
2                      5.2                    1              True
3                      7.6                    4              True
4                      7.6                    4              True
...                    ...                  ...               ...
4495                   7.8                    3              True
4496                   6.6                    3             False
4497                   6.0                    2              True
4498                   7.1                    3             False
4499                   6.8                    3              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
0                         Always                    20.0                   73
1                      Sometimes                    17.0                   90
2                     Frequently                    18.0                   70
3                      Sometimes                    15.0                   82
4                          Never                    16.0                   84
...                          ...                     ...                  ...
4495                   Sometimes                    11.0                   79
4496                  Frequently                     9.0                   83
4497                  Frequently                    13.0                   73
4498                   Sometimes                    22.0                   87
4499                  Frequently                    10.0                   98

      Academic_Performance_GPA Overall_Impact
0                         2.73        Neutral
1                         3.21     Beneficial
2                         3.00        Neutral
3                         3.42     Beneficial
4                         3.41     Beneficial
...                        ...            ...
4495                      2.85     Beneficial
4496                      3.37     Beneficial
4497                      3.16     Beneficial
4498                      3.50     Beneficial
4499                      3.73     Beneficial

[4500 rows x 16 columns]

In [ ]:
#Viewing Data
df.head()
print(df.head(3))

    Student_ID  Age  Gender Academic_Level Primary_Platform  \
0  STU_2024000   19  Female  Undergraduate         Snapchat
1  STU_2024001   19  Female  Undergraduate        Instagram
2  STU_2024002   17  Female    High School           TikTok

   Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  Sleep_Duration_Hours  \
0                7.5                  1.5  Smartphone                   5.9
1                4.6                  1.3  Smartphone                   7.9
2               10.9                  1.7  Smartphone                   5.2

   Sleep_Quality_Score  Late_Night_Usage Social_Comparison_Frequency  \
0                    2              True                      Always
1                    3              True                   Sometimes
2                    1              True                  Frequently

   Perceived_Stress_Score  Mental_Health_Index  Academic_Performance_GPA  \
0                    20.0                   73                      2.73
1                    17.0                   90                      3.21
2                    18.0                   70                      3.00

  Overall_Impact
0        Neutral
1     Beneficial
2        Neutral

In [ ]:
df.tail(2)

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [ ]:
#Shape and Basic Properties
df.shape

(4500, 16)

In [ ]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Primary_Platform',
       'Daily_Usage_Hours', 'Weekend_Extra_Hours', 'Device_Type',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score', 'Late_Night_Usage',
       'Social_Comparison_Frequency', 'Perceived_Stress_Score',
       'Mental_Health_Index', 'Academic_Performance_GPA', 'Overall_Impact'],
      dtype='object')

In [ ]:
print(df.dtypes)

Student_ID                      object
Age                              int64
Gender                          object
Academic_Level                  object
Primary_Platform                object
Daily_Usage_Hours              float64
Weekend_Extra_Hours            float64
Device_Type                     object
Sleep_Duration_Hours           float64
Sleep_Quality_Score              int64
Late_Night_Usage                  bool
Social_Comparison_Frequency     object
Perceived_Stress_Score         float64
Mental_Health_Index              int64
Academic_Performance_GPA       float64
Overall_Impact                  object
dtype: object

In [ ]:
# DataFrame Information
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Student_ID                   4500 non-null   object
 1   Age                          4500 non-null   int64
 2   Gender                       4500 non-null   object
 3   Academic_Level               4500 non-null   object
 4   Primary_Platform             4500 non-null   object
 5   Daily_Usage_Hours            4500 non-null   float64
 6   Weekend_Extra_Hours          4500 non-null   float64
 7   Device_Type                  4500 non-null   object
 8   Sleep_Duration_Hours         4500 non-null   float64
 9   Sleep_Quality_Score          4500 non-null   int64
 10  Late_Night_Usage             4500 non-null   bool
 11  Social_Comparison_Frequency  4500 non-null   object
 12  Perceived_Stress_Score       4454 non-null   float64
 13  Mental_Health_Index          4500 non-null   int64
 14  Academic_Performance_GPA     4415 non-null   float64
 15  Overall_Impact               4500 non-null   object
dtypes: bool(1), float64(5), int64(3), object(7)
memory usage: 531.9+ KB
None

In [ ]:
#Statistical summary
print(df.describe())

               Age  Daily_Usage_Hours  Weekend_Extra_Hours  \
count  4500.000000        4500.000000          4500.000000
mean     18.703333           5.295933             1.796844
std       1.981182           2.604497             0.699245
min      15.000000           0.900000             0.000000
25%      17.000000           3.400000             1.300000
50%      19.000000           4.700000             1.800000
75%      20.000000           6.600000             2.300000
max      26.000000          14.000000             4.500000

       Sleep_Duration_Hours  Sleep_Quality_Score  Perceived_Stress_Score  \
count           4500.000000          4500.000000             4454.000000
mean               6.701333             2.472000               13.512124
std                1.189998             1.030484                7.072859
min                3.000000             1.000000                0.000000
25%                6.000000             2.000000                9.000000
50%                6.800000             3.000000               13.000000
75%                7.500000             3.000000               18.000000
max               10.500000             5.000000               40.000000

       Mental_Health_Index  Academic_Performance_GPA
count          4500.000000               4415.000000
mean             79.873111                  3.429282
std              12.876044                  0.392662
min              32.000000                  1.900000
25%              72.000000                  3.200000
50%              82.000000                  3.460000
75%              89.000000                  3.720000
max              98.000000                  4.000000

In [ ]:
#Selecting columns
print(df["Primary_Platform"])

0        Snapchat
1       Instagram
2          TikTok
3         YouTube
4        LinkedIn
          ...
4495      YouTube
4496     LinkedIn
4497    Instagram
4498     LinkedIn
4499    Instagram
Name: Primary_Platform, Length: 4500, dtype: object

In [ ]:
print(df[["Age","Gender"]])

      Age  Gender
0      19  Female
1      19  Female
2      17  Female
3      16  Female
4      17    Male
...   ...     ...
4495   16    Male
4496   19  Female
4497   19    Male
4498   16    Male
4499   24    Male

[4500 rows x 2 columns]

In [ ]:
#Selecting Rows — loc and iloc
print(df.loc[1])

Student_ID                       STU_2024001
Age                                       19
Gender                                Female
Academic_Level                 Undergraduate
Primary_Platform                   Instagram
Daily_Usage_Hours                        4.6
Weekend_Extra_Hours                      1.3
Device_Type                       Smartphone
Sleep_Duration_Hours                     7.9
Sleep_Quality_Score                        3
Late_Night_Usage                        True
Social_Comparison_Frequency        Sometimes
Perceived_Stress_Score                  17.0
Mental_Health_Index                       90
Academic_Performance_GPA                3.21
Overall_Impact                    Beneficial
Name: 1, dtype: object

In [ ]:
print(df.loc[1,"Age"])

19

In [ ]:
#iloc
print(df.iloc[2])

Student_ID                     STU_2024002
Age                                     17
Gender                              Female
Academic_Level                 High School
Primary_Platform                    TikTok
Daily_Usage_Hours                     10.9
Weekend_Extra_Hours                    1.7
Device_Type                     Smartphone
Sleep_Duration_Hours                   5.2
Sleep_Quality_Score                      1
Late_Night_Usage                      True
Social_Comparison_Frequency     Frequently
Perceived_Stress_Score                18.0
Mental_Health_Index                     70
Academic_Performance_GPA               3.0
Overall_Impact                     Neutral
Name: 2, dtype: object

In [ ]:
print(df.iloc[4,3])

High School

In [ ]:
#10.Filtering Data
licence = df[df["Age"]>=18]
print(licence)

       Student_ID  Age  Gender Academic_Level Primary_Platform  \
0     STU_2024000   19  Female  Undergraduate         Snapchat
1     STU_2024001   19  Female  Undergraduate        Instagram
6     STU_2024006   20    Male  Undergraduate           TikTok
7     STU_2024007   19  Female  Undergraduate           TikTok
8     STU_2024008   18  Female  Undergraduate          YouTube
...           ...  ...     ...            ...              ...
4492  STU_2028492   22    Male   Postgraduate         Snapchat
4493  STU_2028493   18  Female  Undergraduate          YouTube
4496  STU_2028496   19  Female  Undergraduate         LinkedIn
4497  STU_2028497   19    Male  Undergraduate        Instagram
4499  STU_2028499   24    Male  Undergraduate        Instagram

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
0                   7.5                  1.5  Smartphone
1                   4.6                  1.3  Smartphone
6                   5.6                  1.8  Smartphone
7                   1.2                  2.4  Smartphone
8                   3.3                  1.8  Smartphone
...                 ...                  ...         ...
4492                3.6                  2.5  Smartphone
4493                4.5                  2.4  Smartphone
4496                3.8                  3.0  Smartphone
4497                7.7                  1.1  Smartphone
4499                1.8                  2.1  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
0                      5.9                    2              True
1                      7.9                    3              True
6                      8.3                    3             False
7                      8.1                    5             False
8                      6.4                    2             False
...                    ...                  ...               ...
4492                   7.0                    4              True
4493                   8.2                    4              True
4496                   6.6                    3             False
4497                   6.0                    2              True
4499                   6.8                    3              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
0                         Always                    20.0                   73
1                      Sometimes                    17.0                   90
6                      Sometimes                    10.0                   88
7                         Always                     6.0                   95
8                     Frequently                    23.0                   88
...                          ...                     ...                  ...
4492                  Frequently                    11.0                   92
4493                   Sometimes                     0.0                   85
4496                  Frequently                     9.0                   83
4497                  Frequently                    13.0                   73
4499                  Frequently                    10.0                   98

      Academic_Performance_GPA Overall_Impact
0                         2.73        Neutral
1                         3.21     Beneficial
6                         3.72     Beneficial
7                         3.37     Beneficial
8                         3.59     Beneficial
...                        ...            ...
4492                      3.42     Beneficial
4493                      3.75     Beneficial
4496                      3.37     Beneficial
4497                      3.16     Beneficial
4499                      3.73     Beneficial

[3280 rows x 16 columns]

In [ ]:
#11.Adding a new column
df["city"]="Karachi"
df.head()

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact,city
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral,Karachi
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial,Karachi
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral,Karachi
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial,Karachi
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial,Karachi

In [ ]:
#12.Updating values
df.loc[0,"Age"]=25
df

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact,city
0,STU_2024000,25,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral,Karachi
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial,Karachi
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral,Karachi
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial,Karachi
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial,Karachi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial,Karachi
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial,Karachi
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial,Karachi
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial,Karachi
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial,Karachi

In [ ]:
#13Deleting rows and column
df=df.drop("Gender",axis=1)
df=df.drop(4)
df.head()

,Student_ID,Age,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact,city
0,STU_2024000,25,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral,Karachi
1,STU_2024001,19,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial,Karachi
2,STU_2024002,17,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral,Karachi
3,STU_2024003,16,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial,Karachi
5,STU_2024005,16,High School,TikTok,6.2,1.6,Smartphone,5.9,1,False,Rarely,10.0,66,3.21,Beneficial,Karachi

In [ ]:
#14 Handling mising values
df.isnull().sum()

Student_ID                      0
Age                             0
Gender                          0
Academic_Level                  0
Primary_Platform                0
Daily_Usage_Hours               0
Weekend_Extra_Hours             0
Device_Type                     0
Sleep_Duration_Hours            0
Sleep_Quality_Score             0
Late_Night_Usage                0
Social_Comparison_Frequency     0
Perceived_Stress_Score         46
Mental_Health_Index             0
Academic_Performance_GPA       85
Overall_Impact                  0
dtype: int64

In [ ]:
df["Perceived_Stress_Score"]=df["Perceived_Stress_Score"].fillna(0)

In [ ]:
df.isnull().sum()

Student_ID                      0
Age                             0
Gender                          0
Academic_Level                  0
Primary_Platform                0
Daily_Usage_Hours               0
Weekend_Extra_Hours             0
Device_Type                     0
Sleep_Duration_Hours            0
Sleep_Quality_Score             0
Late_Night_Usage                0
Social_Comparison_Frequency     0
Perceived_Stress_Score          0
Mental_Health_Index             0
Academic_Performance_GPA       85
Overall_Impact                  0
dtype: int64

In [ ]:
##15 Handling Duplicate data
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4495    False
4496    False
4497    False
4498    False
4499    False
Length: 4500, dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
#16 Sorting Data
df.sort_values("Age")

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
10,STU_2024010,15,Female,High School,TikTok,4.4,1.9,Smartphone,5.8,2,False,Frequently,11.0,83,3.22,Beneficial
4480,STU_2028480,15,Female,High School,Instagram,5.0,2.3,Tablet,8.8,4,True,Frequently,13.0,87,3.69,Beneficial
2167,STU_2026167,15,Female,High School,Reddit,6.8,1.9,Smartphone,5.0,1,True,Rarely,23.0,66,2.88,Neutral
2345,STU_2026345,15,Female,High School,TikTok,3.8,1.0,Smartphone,8.9,4,True,Sometimes,1.0,98,3.67,Beneficial
50,STU_2024050,15,Female,High School,TikTok,8.6,1.0,Smartphone,6.4,1,True,Rarely,11.0,66,3.38,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3663,STU_2027663,26,Male,Postgraduate,Instagram,3.4,2.2,Smartphone,7.5,4,False,Sometimes,17.0,92,3.25,Beneficial
3610,STU_2027610,26,Male,Postgraduate,TikTok,7.9,2.9,Smartphone,6.3,1,True,Sometimes,13.0,64,3.26,Beneficial
59,STU_2024059,26,Female,Undergraduate,Instagram,3.1,2.4,Smartphone,8.4,4,True,Sometimes,5.0,90,4.00,Beneficial
1104,STU_2025104,26,Female,Undergraduate,TikTok,8.0,1.8,Smartphone,4.7,1,False,Always,19.0,52,3.17,Neutral
3763,STU_2027763,26,Male,Postgraduate,TikTok,3.6,2.9,Smartphone,8.7,4,False,Sometimes,0.0,98,4.00,Beneficial

In [ ]:
df.sort_values("Age",ascending=False)

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
1419,STU_2025419,26,Female,Postgraduate,Instagram,3.9,1.4,Laptop/PC,8.3,3,False,Rarely,9.0,87,3.84,Beneficial
59,STU_2024059,26,Female,Undergraduate,Instagram,3.1,2.4,Smartphone,8.4,4,True,Sometimes,5.0,90,4.00,Beneficial
2761,STU_2026761,26,Male,Undergraduate,TikTok,4.7,1.5,Smartphone,5.6,1,True,Frequently,12.0,81,3.74,Beneficial
1447,STU_2025447,26,Male,Postgraduate,Snapchat,5.8,1.9,Smartphone,7.2,3,False,Frequently,14.0,85,3.48,Beneficial
2748,STU_2026748,26,Male,Undergraduate,Instagram,3.4,1.1,Smartphone,8.3,4,True,Sometimes,11.0,94,3.48,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1799,STU_2025799,15,Male,High School,TikTok,1.5,3.5,Smartphone,8.5,4,True,Frequently,5.0,98,NaN,Beneficial
3220,STU_2027220,15,Male,High School,Snapchat,7.0,1.5,Smartphone,5.1,1,True,Sometimes,22.0,52,3.33,Neutral
3228,STU_2027228,15,Female,High School,TikTok,1.9,0.8,Smartphone,7.9,3,True,Frequently,0.0,98,4.00,Beneficial
3242,STU_2027242,15,Female,High School,Snapchat,5.1,1.9,Smartphone,6.1,3,True,Rarely,17.0,80,3.28,Beneficial
10,STU_2024010,15,Female,High School,TikTok,4.4,1.9,Smartphone,5.8,2,False,Frequently,11.0,83,3.22,Beneficial

In [ ]:
#17 Aggregation and Groupby
result = df.groupby("Primary_Platform")["Daily_Usage_Hours"].mean()
print(result)

Primary_Platform
Instagram      5.261390
LinkedIn       5.267708
Reddit         5.313974
Snapchat       5.457415
TikTok         5.330995
X (Twitter)    5.143204
YouTube        5.248289
Name: Daily_Usage_Hours, dtype: float64

In [ ]:
result = df.groupby("Sleep_Duration_Hours")["Daily_Usage_Hours"].sum()
print(result)

Sleep_Duration_Hours
3.0     146.1
3.1      39.1
3.2      64.3
3.3     105.3
3.4      42.5
        ...
9.8       5.9
10.0      8.6
10.1      4.5
10.4      1.4
10.5      1.3
Name: Daily_Usage_Hours, Length: 73, dtype: float64

In [ ]:
#18. Combinig data frames
df1 = {
    "Platform" : ["Instagram","TikTok","Reddit","Youtube"],
    "Daily_usage_hours" : [4,3,1,2]
}

df2 = {
    "Platform" : ["Linkedin","Snapchat","Facebook","Whatsapp","Discord"],
    "Daily_usage_hours" : [3,2,1,5,3]
}

df1 = pd.DataFrame(df1)
df2 = pd.DataFrame(df2)
print("=====DF1======")
print(df1)
print("======DF======")
print(df2)

=====DF1======
    Platform  Daily_usage_hours
0  Instagram                  4
1     TikTok                  3
2     Reddit                  1
3    Youtube                  2
======DF======
   Platform  Daily_usage_hours
0  Linkedin                  3
1  Snapchat                  2
2  Facebook                  1
3  Whatsapp                  5
4   Discord                  3

In [ ]:
final_result=pd.concat([df1,df2],ignore_index=True)
print(final_result)

    Platform  Daily_usage_hours
0  Instagram                  4
1     TikTok                  3
2     Reddit                  1
3    Youtube                  2
4   Linkedin                  3
5   Snapchat                  2
6   Facebook                  1
7   Whatsapp                  5
8    Discord                  3

In [ ]:
students={"ID":[1,2,3],"Name":["Ali","Sara","Ahmed"]}
marks={"ID":[1,2,3],"Marks":[70,85,60]}
df1=pd.DataFrame(students)
df2=pd.DataFrame(marks)
print(df1)
print(df2)

   ID   Name
0   1    Ali
1   2   Sara
2   3  Ahmed
   ID  Marks
0   1     70
1   2     85
2   3     60

In [ ]:
#merge
final_result=pd.merge(df1,df2,on="ID")
print(final_result)

   ID   Name  Marks
0   1    Ali     70
1   2   Sara     85
2   3  Ahmed     60

**Task#1**

In [ ]:
#create this student marks
data={"Name":["Ali","Sara","Ahmed","Ayesha","Zain"],"Marks":[70,85,60,95,45]}
df= pd.DataFrame(data)
print("====Student Data=====")
print(df)
print("-----Average-----")
print(df["Marks"].mean())
print("-----Maximum-----")
print(df["Marks"].max())
print("-----Minimum-----")
print(df["Marks"].min())
print("~~~~~Total students~~~~~")
print(df.count())
len(df)

====Student Data=====
     Name  Marks
0     Ali     70
1    Sara     85
2   Ahmed     60
3  Ayesha     95
4    Zain     45
-----Average-----
71.0
-----Maximum-----
95
-----Minimum-----
45
~~~~~Total students~~~~~
Name     5
Marks    5
dtype: int64

5

**Task#2**

In [ ]:
print("====passed====")
passed=df[df["Marks"]>=50]
print(passed)
print("====failed====")
failed=df[df["Marks"]<50]
print(failed)

====passed====
     Name  Marks
0     Ali     70
1    Sara     85
2   Ahmed     60
3  Ayesha     95
====failed====
   Name  Marks
4  Zain     45

**Task#3**

In [ ]:
#Task3
df["city"]=["Karachi","Lahore","Multan","Karachi","Punjab"]
print(df)
print("====Karachi====")
karachi=df[df["city"]=="Karachi"]
print(karachi)

     Name  Marks     city
0     Ali     70  Karachi
1    Sara     85   Lahore
2   Ahmed     60   Multan
3  Ayesha     95  Karachi
4    Zain     45   Punjab
====Karachi====
     Name  Marks     city
0     Ali     70  Karachi
3  Ayesha     95  Karachi

**Task#4**

In [ ]:
data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha","Kiran"],
    "Course": ["AI", "Web", "AI", "Web","AI"],
    "Marks": [80, 90, 70, 85,95]
}

df = pd.DataFrame(data)
print(df)
print("====Average Marks====")
result=df.groupby("Course")["Marks"].mean()
print(result)

     Name Course  Marks
0     Ali     AI     80
1    Sara    Web     90
2   Ahmed     AI     70
3  Ayesha    Web     85
4   Kiran     AI     95
====Average Marks====
Course
AI     81.666667
Web    87.500000
Name: Marks, dtype: float64

**Task#5**

In [ ]:
data={"Name":["Ali","Sara","Ahmed","Ayesha","Zain"],"Marks":[80,None,70,None,90]}
df= pd.DataFrame(data)
print("====Student Data=====")
print(df)
print("===Null values====")
print(df.isnull().sum())
print("===Filled values====")
df["Marks"]=df["Marks"].fillna(df["Marks"].mean())
print(df)

====Student Data=====
     Name  Marks
0     Ali   80.0
1    Sara    NaN
2   Ahmed   70.0
3  Ayesha    NaN
4    Zain   90.0
===Null values====
Name     0
Marks    2
dtype: int64
===Filled values====
     Name  Marks
0     Ali   80.0
1    Sara   80.0
2   Ahmed   70.0
3  Ayesha   80.0
4    Zain   90.0